---

- name: aaa server example
  hosts: n9kvswitchfcs

  tasks:

# Tacacs Server Basic settings
  - name: "Tacacs Server Basic settings"
    nxos_aaa_server: server_type=tacacs timeout=8 deadtime=19 directed_request=disabled host={{ inventory_hostname }}
