---
- hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - vars/creds.yml
    - vars/tenant_vars.yml
  tasks:

  - name: Build ACI tenant
    aci_rest:
      hostname: "{{ apic_ip }}"
      username: "{{ apic_username }}"
      password: "{{ apic_password }}"
      use_ssl: no
      validate_certs: no
      path: /api/mo/uni.xml
      method: post
      content: |
        <fvTenant name="{{ Tenant }}">

          <fvCtx name="{{ vrf }}"/>

          <fvBD name="{{ bd }}">
            <fvSubnet ip="{{ bd_ip }}"/>
            <fvRsCtx tnFvCtxName="{{ vrf }}"/>
          </fvBD>

          <vzFilter name="HTTP-Filter">
            <vzEntry name="HTTP-Port" dFromPort="http" dToPort="http" etherT="ip" prot="6"/>
          </vzFilter>
          <vzFilter name="HTTPS-Filter">
            <vzEntry name="HTTPS-Port" dFromPort="https" dToPort="https" etherT="ip" prot="6"/>
          </vzFilter>
          <vzFilter name="Ping-Filter">
            <vzEntry name="ICMP" etherT="ip" prot="icmp"/>
          </vzFilter>
          <vzFilter name="Telnet-Filter">
              <vzEntry name="Telnet-Port" dFromPort="23" dToPort="23" etherT="ip" prot="6"/>
          </vzFilter>
          <vzFilter name="SSH-Filter">
            <vzEntry name="SSH-Port" dFromPort="22" dToPort="22" etherT="ip" prot="6"/>
          </vzFilter>
          <vzFilter name="All-IP-Filter">
            <vzEntry name="All-IP-Entry" etherT="ip"/>
          </vzFilter>

          <vzBrCP name="{{ Contract }}">
            <vzSubj name="{{ subj_default }}">
              <vzRsSubjFiltAtt tnVzFilterName="HTTP-Filter"/>
              <vzRsSubjFiltAtt tnVzFilterName="Ping-Filter"/>
            </vzSubj>
          </vzBrCP>

          <fvAp name="{{ AppProfile }}">
            <fvAEPg name="{{ ClientEPG }}">
              <fvRsDomAtt tDn="uni/vmmp-VMware/dom-{{ apic_VMM }}" instrImedcy="immediate" resImedcy="immediate"/>
              <fvRsBd tnFvBDName="{{ bd }}"/>
              <fvRsCons tnVzBrCPName="{{ Contract }}"/>
            </fvAEPg>
            <fvAEPg name="{{ ServerEPG }}">
              <fvRsDomAtt tDn="uni/vmmp-VMware/dom-{{ apic_VMM }}" instrImedcy="immediate" resImedcy="immediate"/>
              <fvRsBd tnFvBDName="{{ bd }}"/>
              <fvRsProv tnVzBrCPName="{{ Contract }}"/>
            </fvAEPg>
          </fvAp>

        </fvTenant> 