---
- hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - vars/creds.yml
    - vars/tenant_vars.yml
  roles:
    - role: avinetworks.avisdk
  tasks:

    - name: Avi Application | Setup App1
      include_role:
        name: avinetworks.aviconfig
      vars:
        avi_config_file: "app_config.yml"
        avi_creds_file: "vars/creds.yml"