---
- hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - vars/creds.yml   
    - vars/tenant_vars.yml
  vars_prompt:
  - name: "user_vm"
    prompt: "nom de la VM a attacher"
    default: "App3"
    private: no
  - name: "user_tenant"
    prompt: "Tenant"
    default: "Demo"
    private: no
  - name: "user_ap"
    prompt: "Application Profile"
    default: "MyNewApp"
    private: no
  - name: "user_epg"
    prompt: "EPG"
    default: "App"
    private: no

  tasks:

  - name: Change VM PG for a given VM
    vmware_guest:
      hostname: "{{ vcenter_ip }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      name: "{{ user_vm }}"
      datacenter: "{{ vcenter_dc }}"
      folder: "{{ vcenter_vm_folder }}"
      state: present
      networks:
      - name: "{{ user_tenant }}|{{ user_ap }}|{{ user_epg }}"