---
- hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - vars/creds.yml   
    - vars/tenant_vars.yml
  tasks:

  - name: Detach VMs from ACI PGs
    vmware_guest:
      hostname: "{{ vcenter_ip }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      name: "{{ item }}"
      datacenter: "{{ vcenter_dc }}"
      folder: "{{ vcenter_vm_folder }}"
      state: present
      networks:
      - name: "VM Network"
    with_items:
      - "{{ Frontends }}"
      - "{{ Backends }}"
      - Bastion