---
- hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - vars/creds.yml   
    - vars/tenant_vars.yml
  vars_prompt:
  - name: "user_vm"
    prompt: "nom de la VM a detacher"
    default: "App3"
    private: no

  tasks:

  - name: Detach VMs from ACI PGs
    vmware_guest:
      hostname: "{{ vcenter_ip }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      name: "{{ user_vm }}"
      datacenter: "{{ vcenter_dc }}"
      folder: "{{ vcenter_vm_folder }}"
      state: present
      networks:
      - name: "VM Network"