---
#- import_playbook: 00_build_aci_tenant.yml

- import_playbook: 03_import_avi_ldev.yml

- hosts: localhost
  gather_facts: no
  tasks:
  - pause:
      seconds: 2

- import_playbook: 04_create_network_ranges.yml

- hosts: localhost
  gather_facts: no
  tasks:
  - pause:
      seconds: 5

- import_playbook: 05_create_avi_application.yml

- import_playbook: 06_attach_web_app_vm.yml

- import_playbook: 07_apply_avi_sg.yml