---
- hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - vars/creds.yml
    - vars/tenant_vars.yml
  tasks:

  - name: Create BDs for Fortigate inbound/outbound NICs
    aci_rest:
      hostname: "{{ apic_ip }}"
      username: "{{ apic_username }}"
      password: "{{ apic_password }}"
      use_ssl: no
      validate_certs: no
      path: /api/mo/uni.xml
      method: post
      content: |
        <fvTenant name="{{ Tenant }}">

          <fvBD name="FGT-Internal-BD">
            <fvRsCtx tnFvCtxName="{{ vrf }}"/>
            <fvSubnet ip="{{ fgt_gw_in }}/{{ fgt_mask_in }}"/>
          </fvBD>

          <fvBD name="FGT-External-BD">
            <fvSubnet ip="{{ fgt_gw_out }}/{{ fgt_mask_out }}"/>
            <fvRsCtx tnFvCtxName="{{ vrf }}"/>
          </fvBD>

        </fvTenant>