---
- hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - vars/creds.yml
    - vars/tenant_vars.yml
  tasks:

  - name: Apply Fortigate Service Graph
    aci_rest:
      hostname: "{{ apic_ip }}"
      username: "{{ apic_username }}"
      password: "{{ apic_password }}"
      use_ssl: no
      validate_certs: no
      path: /api/mo/uni.xml
      method: post
      content: |
        <fvTenant name="{{ Tenant }}">

          <fvAp name="{{ AppProfile }}">
            <fvAEPg name="{{ ClientEPG }}">

              <vnsFolderInst ctrctNameOrLbl="{{ fgt_contract }}" graphNameOrLbl="{{ fgt_sg }}" key="Network" locked="no" name="Network" nodeNameOrLbl="FGT-Node" scopedBy="epg"/>

              <vnsFolderInst ctrctNameOrLbl="{{ fgt_contract }}" graphNameOrLbl="{{ fgt_sg }}" key="StaticRoutesFolder" locked="no" name="StaticRoutesFolder" nodeNameOrLbl="FGT-Node" scopedBy="epg">

                <vnsFolderInst ctrctNameOrLbl="{{ fgt_contract }}" graphNameOrLbl="{{ fgt_sg }}" key="IPv4DeviceRouter" locked="no" name="static-route-to-internal" nodeNameOrLbl="FGT-Node" scopedBy="epg">
                  <vnsParamInst key="SequenceNumber" locked="no" mandatory="no" name="SequenceNumber" value="1"/>
                  <vnsParamInst key="Priority" locked="no" mandatory="no" name="AdministrativePriority" value="20"/>
                  <vnsParamInst key="Distance" locked="no" mandatory="no" name="Distance" value="10"/>
                  <vnsParamInst key="DeviceInterface" locked="no" mandatory="no" name="DeviceInterface" value="internal"/>
                  <vnsParamInst key="GatewayIPAddress" locked="no" mandatory="no" name="GatewayIPAddress" value="{{ fgt_gw_in }}"/>
                  <vnsParamInst key="DestinationIPAddress" locked="no" mandatory="no" name="DestinationIPAddress" value="0.0.0.0"/>
                  <vnsParamInst key="DestinationNetmask" locked="no" mandatory="no" name="DestinationNetmask" value="0.0.0.0"/>
                  <vnsParamInst key="Weight" locked="no" mandatory="no" name="AdministrativeWeight" value="0"/>
                </vnsFolderInst>

                <vnsFolderInst ctrctNameOrLbl="{{ fgt_contract }}" graphNameOrLbl="{{ fgt_sg }}" key="IPv4DeviceRouter" locked="no" name="static-route-to-external" nodeNameOrLbl="FGT-Node" scopedBy="epg">
                  <vnsParamInst key="SequenceNumber" locked="no" mandatory="no" name="SequenceNumber" value="2"/>
                  <vnsParamInst key="Priority" locked="no" mandatory="no" name="Priority" value="10"/>
                  <vnsParamInst key="Distance" locked="no" mandatory="no" name="Distance" value="10"/>
                  <vnsParamInst key="DeviceInterface" locked="no" mandatory="no" name="DeviceInterface" value="external"/>
                  <vnsParamInst key="GatewayIPAddress" locked="no" mandatory="no" name="GatewayIPAddress" value="{{ fgt_gw_out }}"/>
                  <vnsParamInst key="DestinationIPAddress" locked="no" mandatory="no" name="DestinationIPAddress" value="0.0.0.0"/>
                  <vnsParamInst key="DestinationNetmask" locked="no" mandatory="no" name="DestinationNetmask" value="0.0.0.0"/>
                  <vnsParamInst key="Weight" locked="no" mandatory="no" name="Weight" value="0"/>
                </vnsFolderInst>
              </vnsFolderInst>

              <vnsFolderInst ctrctNameOrLbl="{{ fgt_contract }}" graphNameOrLbl="{{ fgt_sg }}" key="DeviceInterface" locked="no" name="internal" nodeNameOrLbl="FGT-Node" scopedBy="epg">
                <vnsParamInst key="mode" locked="no" mandatory="no" name="mode" value="static"/>
                <vnsParamInst key="IPAddress" locked="no" mandatory="no" name="IPAddress" value="{{ fgt_ip_in }}"/>
                <vnsParamInst key="IPNetmask" locked="no" mandatory="no" name="IPNetmask" value="{{ fgt_mask_in_binary }}"/>
                <vnsFolderInst ctrctNameOrLbl="{{ fgt_contract }}" graphNameOrLbl="{{ fgt_sg }}" key="AllowAccess" locked="no" name="AllowAccess-Default" nodeNameOrLbl="FGT-Node" scopedBy="epg"/>
              </vnsFolderInst>

              <vnsFolderInst ctrctNameOrLbl="{{ fgt_contract }}" graphNameOrLbl="{{ fgt_sg }}" key="DeviceInterface" locked="no" name="external" nodeNameOrLbl="FGT-Node" scopedBy="epg">
                <vnsParamInst key="mode" locked="no" mandatory="no" name="mode" value="static"/>
                <vnsParamInst key="IPAddress" locked="no" mandatory="no" name="IPAddress" value="{{ fgt_ip_out }}"/>
                <vnsParamInst key="IPNetmask" locked="no" mandatory="no" name="IPNetmask" value="{{ fgt_mask_out_binary }}"/>
                <vnsFolderInst ctrctNameOrLbl="{{ fgt_contract }}" graphNameOrLbl="{{ fgt_sg }}" key="AllowAccess" locked="no" name="AllowAccess-Default" nodeNameOrLbl="FGT-Node" scopedBy="epg"/>
              </vnsFolderInst>

              <vnsFolderInst ctrctNameOrLbl="{{ fgt_contract }}" graphNameOrLbl="{{ fgt_sg }}" key="VDOM-Folder" locked="no" name="vdom-folder" nodeNameOrLbl="FGT-Node" scopedBy="epg">
                <vnsParamInst key="hybrid" locked="no" mandatory="no" name="hybrid" value="YES"/>
                <vnsCfgRelInst key="VDOM-Interface-external" locked="no" mandatory="no" name="VDOM-Interface-external" targetName="external"/>
                <vnsCfgRelInst key="VDOM-Interface-internal" locked="no" mandatory="no" name="VDOM-Interface-internal" targetName="internal"/>
              </vnsFolderInst>

            </fvAEPg>
          </fvAp>

          <vnsLDevCtx ctrctNameOrLbl="{{ fgt_contract }}" graphNameOrLbl="{{ fgt_sg }}" nodeNameOrLbl="FGT-Node">
            <vnsRsLDevCtxToLDev tDn="uni/tn-{{ Tenant }}/lDevVip-FGT"/>
            
            <vnsLIfCtx connNameOrLbl="provider">
              <vnsRsLIfCtxToSvcRedirectPol tDn="uni/tn-{{ Tenant }}/svcCont/svcRedirectPol-FGT-PBR-Policy-External"/>
              <vnsRsLIfCtxToLIf tDn="uni/tn-{{ Tenant }}/lDevVip-FGT/lIf-FGT-External"/>
              <vnsRsLIfCtxToBD tDn="uni/tn-{{ Tenant }}/BD-FGT-External-BD"/>
            </vnsLIfCtx>
            
            <vnsLIfCtx connNameOrLbl="consumer">
              <vnsRsLIfCtxToSvcRedirectPol tDn="uni/tn-{{ Tenant }}/svcCont/svcRedirectPol-FGT-PBR-Policy-Internal"/>
              <vnsRsLIfCtxToLIf tDn="uni/tn-{{ Tenant }}/lDevVip-FGT/lIf-FGT-Internal"/>
              <vnsRsLIfCtxToBD tDn="uni/tn-{{ Tenant }}/BD-FGT-Internal-BD"/>
            </vnsLIfCtx>
          </vnsLDevCtx>

          <vzBrCP name="{{ fgt_contract }}">
            <vzSubj name="{{ subj_to_fgt }}">
              <vzRsSubjGraphAtt tnVnsAbsGraphName="{{ fgt_sg }}"/>
            </vzSubj>
          </vzBrCP>

        </fvTenant>