---
- hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - vars/creds.yml
    - vars/tenant_vars.yml
  tasks:

  - name: Create ASAv PBR Policy
    aci_rest:
      hostname: "{{ apic_ip }}"
      username: "{{ apic_username }}"
      password: "{{ apic_password }}"
      use_ssl: no
      validate_certs: no
      path: /api/mo/uni.xml
      method: post
      content: |
        <fvTenant name="{{ Tenant }}">
          <vnsSvcCont>
            <vnsSvcRedirectPol name="ASAv-PBR-Policy-OneArm">
              <vnsRedirectDest ip="10.203.0.1" mac="00:50:56:aa:bc:0d"/>
            </vnsSvcRedirectPol>
          </vnsSvcCont>
        </fvTenant>