---
- name: Create L3VNI
  hosts: nxos_vteps_cli
  gather_facts: false
  tasks:

    - name: Create VLAN/L3VNI
      nxos_vlan:
        vlan_id: "{{ vrf_vlan }}"
        name: "{{ vrf_name }}-{{ vrf_vni }}"
        mapped_vni: "{{ vrf_vni }}"
        admin_state: up

    - name: Create VRF/L3VNI
      nxos_vrf:
        name: "{{ vrf_name }}-{{ vrf_vni }}"
        rd: auto
        vni: "{{ vrf_vni }}"
        admin_state: up

    - name: Configure VRF Address Family
      nxos_vrf_af:
        vrf: "{{ vrf_name }}-{{ vrf_vni }}"
        afi: ipv4
        safi: unicast
        route_target_both_auto_evpn: True

    - name: Configure VRF/L3VNI SVI
      nxos_interface:
        name: "Vlan{{ vrf_vlan }}"
        description: "{{ vrf_name }}-{{ vrf_vni }}-IP-Forwarder"
        ip_forward: enable
        mtu: "{{ mtu }}"
        admin_state: up

    - name: Create and associate SVI to VRF/L3VNI
      nxos_vrf_interface:
        vrf: "{{ vrf_name }}-{{ vrf_vni }}"
        interface: "Vlan{{ vrf_vlan }}"

    - name: Add VPNv4 AF to BGP (control plane)
      nxos_bgp_af:
        asn: "{{ fabric_asn }}"
        vrf: "{{ vrf_name }}-{{ vrf_vni }}"
        afi: ipv4
        safi: unicast        
        advertise_l2vpn_evpn: yes
        maximum_paths_ibgp: 2
        redistribute: [['direct', 'fabric-rmap-redist-subnet']]

    - name: Add EVPN AF to BGP (control plane)
      nxos_bgp_af:
        asn: "{{ fabric_asn }}"
        afi: l2vpn
        safi: evpn

    - name: Add L3VNI to NVE interface (data plane)
      nxos_vxlan_vtep_vni:
        interface: nve1
        vni: "{{ vrf_vni }}"
        assoc_vrf: True