---
# NetCentric Demo playbook - Delete tenant
- name: Delete Tenant
  hosts: localhost
  gather_facts: no
  vars_files:
    - vars/creds.yml

  vars_prompt:
  - name: "user_tenant"
    prompt: "Tenant to delete"
    default: "none"
    private: no

  tasks:
  - name: Delete Tenant
    aci_tenant:
      hostname: "{{ apic_ip }}"
      username: "{{ apic_username }}"
      password: "{{ apic_password }}"
      validate_certs: no
      use_ssl: no
      tenant: "{{ user_tenant }}"
      state: absent