---

features:
  - { feature: tacacs }
  - { feature: bgp }
  - { feature: udld }
  - { feature: interface-vlan }
  - { feature: bfd }

vlans:
  - { vlan_range: 10-40 }

tacacs:
  - { server: 172.16.100.100 }
  - { server: 172.16.200.110 }
  - { server: 10.20.30.40 }
  
name_servers:
  - { server: 172.16.200.100 }
  - { server: 172.16.200.110 }

trunk_port_profiles:
  - { name: docker , description: "Docker",  mode: trunk, trunk_vlans: 11-20, native_vlan: 11, acl: docker_acl }
  - { name: esxi, description: "ESXi", mode: trunk, trunk_vlans: 21-30, native_vlan: 21, acl: esxi_acl }
  - { name: hyperv, description: "HyperV", mode: trunk, trunk_vlans: 31-40, native_vlan: 31, acl: hyperv_acl }

access_port_profiles:
  - { name: kvm, description: "KVM",mode: access, access_vlan: 10, acl: kvm_acl }

acls:
  - { name: docker_acl , src: 11.11.11.0/24,  dest: 23.23.23.23/24, seq: 10, action: deny, proto: ip }
  - { name: docker_acl , src: 12.12.12.0/24,  dest: 23.23.23.23/24, seq: 15, action: permit, proto: ip }  

  - { name: esxi_acl, src: 12.11.11.0/24,  dest: 24.24.24.24/24, seq: 10, action: deny, proto: ip }
  - { name: esxi_acl, src: 12.12.11.0/24,  dest: 24.24.24.24/24, seq: 10, action: permit, proto: ip }

  - { name: hyperv_acl, src: 13.11.11.0/24,  dest: 25.25.25.25/24, seq: 10, action: permit, proto: ip }
  - { name: kvm_acl, src: 13.11.11.0/24,  dest: 26.26.26.26/24, seq: 10, action: permit, proto: ip }



