---
### BGP ASN is unique per Leaf when chosing eBGP as the underlay protocol (one BGP ASN per Leaf)
fabric_asn: 65000

### access port vars
access_ports:
  - {port_name: Ethernet1/3, port_mode: trunk, port_desc: "*** test Ansible ***"}
  - {port_name: Ethernet1/4, port_mode: trunk, port_desc: "*** test Ansible ***"}