---
- hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - vars/creds.yml   
    - vars/tenant_vars.yml
  tasks:

  - name: Change VM PG for bastion VM
    vmware_guest:
      hostname: "{{ vcenter_ip }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      name: Bastion
      datacenter: "{{ vcenter_dc }}"
      folder: "{{ vcenter_vm_folder }}"
      state: present
      networks:
      - name: "{{ Tenant }}|Admin-Zone|Bastion"